# Generated by Django 4.1.7 on 2023-05-12 14:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0001_initial'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='customuser',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        # ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tlf',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
