# Generated by Django 4.1.7 on 2023-05-12 21:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('customUser', '0003_alter_customuser_id'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='customuser',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
    ]
