# Generated by Django 4.1.7 on 2023-03-20 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('hour', models.TimeField(null=True)),
                ('professional_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professionals.professionals')),
            ],
        ),
    ]
