# Generated by Django 4.1.7 on 2023-05-12 00:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professionals', '0007_alter_professionals_admission_date'),
        ('services', '0001_initial'),
        ('meet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('date', models.DateField(null=True)),
                ('hour', models.TimeField(null=True)),
                ('activa', models.BooleanField(default=True)),
                ('professionals_name', models.CharField(default='', max_length=250, null=True)),
                ('CustomUser_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('professional_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='professionals.professionals')),
                ('service_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='services.service')),
            ],
        ),
    ]
