# Generated by Django 4.1.7 on 2023-05-13 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='CustomUser_id',
            new_name='User',
        ),
        migrations.RenameField(
            model_name='meet',
            old_name='hour',
            new_name='end_time',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='professionals_name',
        ),
        migrations.AddField(
            model_name='meet',
            name='start_time',
            field=models.TimeField(null=True),
        ),
    ]
