# Generated by Django 4.1.7 on 2023-05-13 16:52

import app.meet.models
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0003_rename_customuser_id_meet_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='professional_id',
            new_name='professional_name',
        ),
        migrations.RenameField(
            model_name='meet',
            old_name='User',
            new_name='user_name',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='activa',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='service_id',
        ),
        migrations.AddField(
            model_name='meet',
            name='cancelada',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='scheduled', max_length=50),
        ),
        migrations.AlterField(
            model_name='meet',
            name='date',
            field=models.DateField(null=True, validators=[app.meet.models.future_date_validator]),
        ),
        migrations.AlterField(
            model_name='meet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
