# Generated by Django 4.1.7 on 2023-03-21 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0004_meet_service_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meet',
            name='professional_name',
            field=models.CharField(default='', max_length=250, null=True),
        ),
    ]
