# Generated by Django 4.1.7 on 2023-05-26 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_meet_name_service'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='professional_name',
            new_name='professional',
        ),
        migrations.RenameField(
            model_name='meet',
            old_name='user_name',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='meet',
            name='cancelada',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
