# Generated by Django 4.1.7 on 2023-03-21 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0005_meet_professional_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='professional_name',
            new_name='professionals_name',
        ),
    ]
