# Generated by Django 4.1.7 on 2023-05-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_rename_professional_name_meet_professional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='cancelada',
        ),
        migrations.AlterField(
            model_name='meet',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='scheduled', max_length=50),
        ),
    ]
