# Generated by Django 4.1.7 on 2023-03-24 16:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0006_rename_professional_name_meet_professionals_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='activa',
        ),
        migrations.AddField(
            model_name='meet',
            name='cancelada',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='user_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='meet',
            name='professionals_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
