# Generated by Django 4.1.7 on 2023-04-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0007_remove_meet_activa_meet_cancelada_meet_user_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='hour',
            new_name='end_time',
        ),
        migrations.AddField(
            model_name='meet',
            name='start_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='meet',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('canceled', 'Canceled'), ('completed', 'Completed')], default='scheduled', max_length=50),
        ),
    ]
