# Generated by Django 4.1.7 on 2023-04-15 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_password'),
        ('meet', '0008_rename_hour_meet_end_time_meet_start_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meet',
            name='service_id',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='user_id',
        ),
        migrations.AddField(
            model_name='meet',
            name='name_service',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='meet',
            name='user_name2',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='meet',
            name='user_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
