# Generated by Django 4.1.7 on 2023-04-15 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0009_remove_meet_service_id_remove_meet_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meet',
            old_name='professional_id',
            new_name='professional_name',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='professionals_name',
        ),
        migrations.RemoveField(
            model_name='meet',
            name='user_name2',
        ),
    ]
