# Generated by Django 4.1.7 on 2023-04-22 16:00

from django.db import migrations, models
import utils.validation.validate_date


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0010_rename_professional_id_meet_professional_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date',
            field=models.DateField(null=True, validators=[utils.validation.validate_date.validate_date]),
        ),
    ]
