# Generated by Django 4.1.7 on 2023-04-23 15:40

import app.meet.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0011_alter_meet_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='date',
            field=models.DateField(null=True, validators=[app.meet.models.future_date_validator]),
        ),
    ]
