# Generated by Django 4.1.7 on 2023-08-03 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0014_alter_meet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='status',
            field=models.CharField(choices=[('canceled', 'Canceled'), ('scheduled', 'Scheduled'), ('completed', 'Completed')], default='scheduled', max_length=50),
        ),
    ]
