# Generated by Django 4.1.7 on 2023-08-04 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0015_alter_meet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meet',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('scheduled', 'Scheduled'), ('canceled', 'Canceled')], default='scheduled', max_length=50),
        ),
    ]
