# Generated by Django 4.1.7 on 2023-03-21 15:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name_service', models.CharField(max_length=150, unique=True)),
                ('duration', models.DurationField()),
            ],
        ),
    ]
