# Generated by Django 4.1.7 on 2023-03-20 14:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professionals',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('specialty', models.CharField(max_length=150)),
                ('tlf', models.CharField(default='', max_length=200, unique=True)),
                ('admission_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
