# Generated by Django 4.1.7 on 2023-03-20 16:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0002_alter_professionals_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionals',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='professionals',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
