# Generated by Django 4.1.7 on 2023-03-20 17:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0003_alter_professionals_admission_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionals',
            name='admission_date',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
