# Generated by Django 4.1.7 on 2023-03-21 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0004_alter_professionals_admission_date'),
    ]

    operations = [
        # migrations.AlterField(
        #     model_name='professionals',
        #     name='id',
        #     field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        # ),
    ]
