# Generated by Django 4.1.7 on 2023-03-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0006_alter_professionals_admission_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionals',
            name='admission_date',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
