# Generated by Django 4.1.7 on 2023-05-30 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('professionals', '0007_alter_professionals_admission_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='professionals',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='professionals',
            name='name',
        ),
        migrations.RemoveField(
            model_name='professionals',
            name='tlf',
        ),
        migrations.AddField(
            model_name='professionals',
            name='activity',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professionals',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='professionals', to=settings.AUTH_USER_MODEL),
        ),
    ]
