# Generated by Django 4.1.7 on 2023-08-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0008_remove_professionals_lastname_and_more'),
    ]

    # operations = [
    #     migrations.AlterField(
    #         model_name='professionals',
    #         name='id',
    #         field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
    #     ),
    # ]
