# Generated by Django 4.1.7 on 2023-08-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0009_alter_professionals_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionals',
            name='id',
            field=models.BigIntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
