# Generated by Django 4.1.7 on 2023-03-21 14:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=150)),
                ('lastname', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=254, unique=True)),
                ('tlf', models.CharField(default='', max_length=250, unique=True)),
                ('password', models.CharField(default='', max_length=250, unique=True)),
            ],
        ),
    ]
