# Generated by Django 4.1.7 on 2023-04-23 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meet', '0013_alter_meet_user_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0002_alter_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tlf', models.CharField(default='', max_length=90, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
