# Generated by Django 4.1.7 on 2023-04-25 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='tlf',
            field=models.CharField(blank=True, max_length=90, null=True, unique=True),
        ),
    ]
