# Generated by Django 4.1.7 on 2023-05-13 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authtoken', '0003_tokenproxy'),
        ('account', '0002_email_max_length'),
        ('meet', '0013_alter_meet_user_name'),
        ('socialaccount', '0003_extra_data_default_dict'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('users', '0007_user_delete_userprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Client',
        ),
    ]
